CONNECT TO SE3DB3;



SELECT COUNT(*)FROM PLAYER_MAST;

 

SELECT * FROM PLAYER_MAST;



SELECT COUNT(*)FROM SOCCER_COUNTRY;



SELECT COUNT(*)FROM GOAL_DETAILS WHERE GOAL_SCHEDULE = 'ET';



SELECT COUNT(*)FROM GOAL_DETAILS WHERE GOAL_SCHEDULE = 'ST';



SELECT COUNT(*)FROM GOAL_DETAILS WHERE GOAL_SCHEDULE = 'NT';



SELECT COUNT(*)FROM PLAYER_BOOKED WHERE PLAY_SCHEDULE = 'ST';



SELECT COUNT(*)FROM PLAYER_BOOKED WHERE PLAY_SCHEDULE = 'ET';



SELECT MIN(PLAY_DATE)FROM MATCH_MAST;



SELECT MAX(PLAY_DATE)FROM MATCH_MAST;



SELECT COUNTRY_NAME FROM SOCCER_COUNTRY, SOCCER_TEAM, MATCH_DETAILS WHERE MATCH_NO = 1 AND SOCCER_TEAM.TEAM_ID = MATCH_DETAILS.TEAM_ID AND SOCCER_TEAM.COUNTRY_ID = SOCCER_COUNTRY.COUNTRY_ID;



SELECT COUNTRY_NAME FROM SOCCER_COUNTRY, SOCCER_TEAM, MATCH_DETAILS WHERE PLAY_STAGE = 'F' AND MATCH_DETAILS.WIN_LOSE = 'W' AND MATCH_DETAILS.TEAM_ID = SOCCER_TEAM.TEAM_ID AND SOCCER_TEAM.COUNTRY_ID = SOCCER_COUNTRY.COUNTRY_ID;



SELECT DISTINCT COUNTRY_NAME, PENALTY_NO FROM SOCCER_COUNTRY, SOCCER_TEAM, PENALTY_SHOOTOUT, (SELECT TEAM_ID, COUNT(*) PENALTY_NO FROM PENALTY_SHOOTOUT GROUP BY TEAM_ID ) SHOTS WHERE PENALTY_SHOOTOUT.TEAM_ID = SOCCER_TEAM.TEAM_ID AND SOCCER_TEAM.COUNTRY_ID = SOCCER_COUNTRY.COUNTRY_ID AND SHOTS.TEAM_ID = SOCCER_TEAM.TEAM_ID;



SELECT COUNTRY_NAME FROM (SELECT COUNTRY_NAME, TEAM_ID FROM SOCCER_COUNTRY JOIN SOCCER_TEAM ON SOCCER_COUNTRY.COUNTRY_ID = SOCCER_TEAM.COUNTRY_ID) COUNTRIES JOIN (SELECT TEAM_ID FROM MATCH_DETAILS WHERE PLAY_STAGE = 'F') IDS ON COUNTRIES.TEAM_ID = IDS.TEAM_ID;



SELECT PLAY_DATE FROM MATCH_MAST WHERE MATCH_NO in (SELECT MATCH_NO FROM PENALTY_SHOOTOUT);



SELECT VENUE_NAME FROM SOCCER_VENUE WHERE VENUE_ID in (SELECT VENUE_ID FROM MATCH_MAST WHERE MATCH_NO in (SELECT MATCH_NO FROM PENALTY_SHOOTOUT));



SELECT 11 + COUNT(PLAYER_ID) FRENCH FROM (SELECT PLAYER_ID FROM PLAYER_IN_OUT WHERE PLAYER_IN_OUT.MATCH_NO = 51 AND PLAYER_IN_OUT.TEAM_ID = 1907 AND PLAYER_IN_OUT.IN_OUT = 'I');


TERMINATE;





















 
